compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableProgressBars: false

nodeLinker: node-modules

packageExtensions:
  mini-css-extract-plugin@*:
    dependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
